apiVersion: apps/v1
kind: Deployment

metadata:
  name: mlops-demo-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: mlops-demo-api

  template:
    metadata:
      labels:
        app: mlops-demo-api

    spec:
      containers:
        - name: mlops-demo-api
          image: mlops-demo-api:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"