apiVersion: v1
kind: Service

metadata:
  name: mlops-demo-api-service

spec:
  type: NodePort

  selector:
    app: mlops-demo-api

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080